version: "3.9"
services:
  app:
    build: .
    container_name: rag_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHROMA_PATH=/app/data/chroma
      - UPLOAD_DIR=/app/data/uploads
    volumes:
      - ./data:/app/data
    restart: unless-stopped

